### PR TITLE
change trim stuff

### PR DESCRIPTION
**Pull request by SherineAwad**

### CODE REVIEW

**Comment by ctb** [comment]
Hi @SherineAwad, is this target still needed?

`ecoli.pe.qc.fq.gz.pe`

The `ecoli.pe.qc.fq.gz` file is produced by interleave-reads above and should already be perfectly paired, so extract paired reads and the qc-rename-1.sh script call seems like they are no longer needed. Could you verify and report back?

**Comment by SherineAwad** [comment]
Yes, you are right. Won't be needed. And we won't need qc-rename-2.sh too.

**Comment by SherineAwad** [comment]
Yes, you are right. Won't be needed. And we can get rid of qc-rename-2.sh too.

**Comment by ctb** [comment]
Merged into #1.

**Pull request closed without merging**
