### PR TITLE
Some scripts for chimera checking.

### PR DESCRIPTION
**Pull request by ctb**
In addition to some refactoring of `analyze_assembly.py`, this adds a script `split_chimeric.py` which takes all of the contigs and splits them into bits that align completely to the reference, discarding the rest. This should give us some better ways of understanding the misassemblies/

### CODE REVIEW

**Comment by ctb** [comment]
@SherineAwad @luizirber could you check me on this code change, pls?

https://github.com/dib-lab/2015-metagenome-assembly/pull/12/files#diff-8baac0e5b7f645930a4ce8d48fa01f53R119

The goal is to always take the longer of two alignments if they have the same identity.

**Comment by SherineAwad** [comment]
@ctb  looks okay to me. Thanks

**Comment by ctb** [comment]
(See description, above, for details of what split_chimeric does)

Results:

```
python ./split_chimeric.py /mnt/research/ged/sherine/2015-metagenome-assembly/pipeline/{mircea.fa,megahit-quality-assembly500.fa,mqc500.coords}
```

## before splitting:

```
python ./compute_stats.py /mnt/research/ged/sherine/2015-metagenome-assembly/pipeline/{megahit-quality-assembly500.fa,mircea.fa}

Assembly has 200302322 base pairs
Reference has 205603715 base pairs
N50 equals: 41427
NG50 equals: 39206
```

## after splitting:

```
python ./compute_stats.py ./megahit-quality-assembly500.fa.no-chimera.fa /mnt/research/ged/sherine/2015-metagenome-assembly/pipeline/mircea.fa

Assembly has 184223575 base pairs
Reference has 205603715 base pairs
N50 equals: 38125
NG50 equals: 29696
````

**Comment by ctb** [comment]
I'm confused by the dramatic decrease in the NG50 vs the N50.

**Comment by ctb** [comment]
Well, so we're only outputting contigs that map to the reference genome.

And we have an incorrect reference genome, to some extent.

**Comment by SherineAwad** [comment]
@ctb  So you are flagging each alignment; how many times it is mapped to the reference, discard the alignment if it is flagged more than once and keep the rest. Right?

**Comment by ctb** [comment]
On Sun, Apr 09, 2017 at 11:49:59AM -0700, Sherine wrote:
> @ctb  So you are flagging each alignment; how many times it is mapped to the reference, discard the alignment if it is flagged more than once and keep the rest. Right? 

Yep!

**Pull request merged**
